language: node_js

sudo: required

services:
  - docker

node_js:
  - "8.12"

script:
  - yarn flow
  - yarn lint
  - yarn test --coverage
  - yarn build
  - git clean -dfx
  - docker build . -t ipfs_print_hash
  - docker run ipfs_print_hash
