// flow-typed signature: 23475199d20c0368a15c270eb39f329e
// flow-typed version: <<STUB>>/augur-core_v^1.1.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'augur-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'augur-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'augur-core/output/browser' {
  declare module.exports: any;
}

declare module 'augur-core/output/deployment/compileAndDeploy' {
  declare module.exports: any;
}

declare module 'augur-core/output/deployment/compileContracts' {
  declare module.exports: any;
}

declare module 'augur-core/output/deployment/deployContracts' {
  declare module.exports: any;
}

declare module 'augur-core/output/deployment/deployNetworks' {
  declare module.exports: any;
}

declare module 'augur-core/output/index' {
  declare module.exports: any;
}

declare module 'augur-core/output/libraries/AccountManager' {
  declare module.exports: any;
}

declare module 'augur-core/output/libraries/CompilerConfiguration' {
  declare module.exports: any;
}

declare module 'augur-core/output/libraries/Connector' {
  declare module.exports: any;
}

declare module 'augur-core/output/libraries/ContractCompiler' {
  declare module.exports: any;
}

declare module 'augur-core/output/libraries/ContractDeployer' {
  declare module.exports: any;
}

declare module 'augur-core/output/libraries/ContractInterfaces' {
  declare module.exports: any;
}

declare module 'augur-core/output/libraries/ContractInterfacesGenerator' {
  declare module.exports: any;
}

declare module 'augur-core/output/libraries/Contracts' {
  declare module.exports: any;
}

declare module 'augur-core/output/libraries/DeployerConfiguration' {
  declare module.exports: any;
}

declare module 'augur-core/output/libraries/HelperFunctions' {
  declare module.exports: any;
}

declare module 'augur-core/output/libraries/LegacyRepMigrator' {
  declare module.exports: any;
}

declare module 'augur-core/output/libraries/NetworkConfiguration' {
  declare module.exports: any;
}

declare module 'augur-core/output/tests-integration/RepMigration' {
  declare module.exports: any;
}

declare module 'augur-core/output/tests-integration/ReportingUtils' {
  declare module.exports: any;
}

declare module 'augur-core/output/tests-integration/TestFixture' {
  declare module.exports: any;
}

declare module 'augur-core/output/tests-integration/TestRpc' {
  declare module.exports: any;
}

declare module 'augur-core/output/tests-integration/TradeAndReport' {
  declare module.exports: any;
}

declare module 'augur-core/output/tools/generateContractInterfaces' {
  declare module.exports: any;
}

declare module 'augur-core/output/tools/migrateRep' {
  declare module.exports: any;
}

declare module 'augur-core/source/tools/generateCoverageReport' {
  declare module.exports: any;
}

declare module 'augur-core/typings/bn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'augur-core/output/browser.js' {
  declare module.exports: $Exports<'augur-core/output/browser'>;
}
declare module 'augur-core/output/deployment/compileAndDeploy.js' {
  declare module.exports: $Exports<'augur-core/output/deployment/compileAndDeploy'>;
}
declare module 'augur-core/output/deployment/compileContracts.js' {
  declare module.exports: $Exports<'augur-core/output/deployment/compileContracts'>;
}
declare module 'augur-core/output/deployment/deployContracts.js' {
  declare module.exports: $Exports<'augur-core/output/deployment/deployContracts'>;
}
declare module 'augur-core/output/deployment/deployNetworks.js' {
  declare module.exports: $Exports<'augur-core/output/deployment/deployNetworks'>;
}
declare module 'augur-core/output/index.js' {
  declare module.exports: $Exports<'augur-core/output/index'>;
}
declare module 'augur-core/output/libraries/AccountManager.js' {
  declare module.exports: $Exports<'augur-core/output/libraries/AccountManager'>;
}
declare module 'augur-core/output/libraries/CompilerConfiguration.js' {
  declare module.exports: $Exports<'augur-core/output/libraries/CompilerConfiguration'>;
}
declare module 'augur-core/output/libraries/Connector.js' {
  declare module.exports: $Exports<'augur-core/output/libraries/Connector'>;
}
declare module 'augur-core/output/libraries/ContractCompiler.js' {
  declare module.exports: $Exports<'augur-core/output/libraries/ContractCompiler'>;
}
declare module 'augur-core/output/libraries/ContractDeployer.js' {
  declare module.exports: $Exports<'augur-core/output/libraries/ContractDeployer'>;
}
declare module 'augur-core/output/libraries/ContractInterfaces.js' {
  declare module.exports: $Exports<'augur-core/output/libraries/ContractInterfaces'>;
}
declare module 'augur-core/output/libraries/ContractInterfacesGenerator.js' {
  declare module.exports: $Exports<'augur-core/output/libraries/ContractInterfacesGenerator'>;
}
declare module 'augur-core/output/libraries/Contracts.js' {
  declare module.exports: $Exports<'augur-core/output/libraries/Contracts'>;
}
declare module 'augur-core/output/libraries/DeployerConfiguration.js' {
  declare module.exports: $Exports<'augur-core/output/libraries/DeployerConfiguration'>;
}
declare module 'augur-core/output/libraries/HelperFunctions.js' {
  declare module.exports: $Exports<'augur-core/output/libraries/HelperFunctions'>;
}
declare module 'augur-core/output/libraries/LegacyRepMigrator.js' {
  declare module.exports: $Exports<'augur-core/output/libraries/LegacyRepMigrator'>;
}
declare module 'augur-core/output/libraries/NetworkConfiguration.js' {
  declare module.exports: $Exports<'augur-core/output/libraries/NetworkConfiguration'>;
}
declare module 'augur-core/output/tests-integration/RepMigration.js' {
  declare module.exports: $Exports<'augur-core/output/tests-integration/RepMigration'>;
}
declare module 'augur-core/output/tests-integration/ReportingUtils.js' {
  declare module.exports: $Exports<'augur-core/output/tests-integration/ReportingUtils'>;
}
declare module 'augur-core/output/tests-integration/TestFixture.js' {
  declare module.exports: $Exports<'augur-core/output/tests-integration/TestFixture'>;
}
declare module 'augur-core/output/tests-integration/TestRpc.js' {
  declare module.exports: $Exports<'augur-core/output/tests-integration/TestRpc'>;
}
declare module 'augur-core/output/tests-integration/TradeAndReport.js' {
  declare module.exports: $Exports<'augur-core/output/tests-integration/TradeAndReport'>;
}
declare module 'augur-core/output/tools/generateContractInterfaces.js' {
  declare module.exports: $Exports<'augur-core/output/tools/generateContractInterfaces'>;
}
declare module 'augur-core/output/tools/migrateRep.js' {
  declare module.exports: $Exports<'augur-core/output/tools/migrateRep'>;
}
declare module 'augur-core/source/tools/generateCoverageReport.js' {
  declare module.exports: $Exports<'augur-core/source/tools/generateCoverageReport'>;
}
declare module 'augur-core/typings/bn.js' {
  declare module.exports: $Exports<'augur-core/typings/bn'>;
}
