// flow-typed signature: 0c662a7d525b81cb0eabd6d12f06da38
// flow-typed version: <<STUB>>/augur.js_v^5.6.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'augur.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'augur.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'augur.js/dist/augur' {
  declare module.exports: any;
}

declare module 'augur.js/dist/augur.min' {
  declare module.exports: any;
}

declare module 'augur.js/exports' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/connection-endpoints' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/core-version' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/decrypt-keystore' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/cancel-orders' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/create-markets' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/create-orders' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/fill-order' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/fund-accounts' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/index' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/approve-augur-eternal-approval-value' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/cancel-order' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/cancel-orders' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/create-market' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/create-markets' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/create-order-book' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/create-order' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/create-orders' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/fill-both-order-types' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/fill-order' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/fund-accounts' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/get-balances' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/get-order-to-fill' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/get-private-key' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/print-transaction-status' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/select-canned-market' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/lib/verify-order-book' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/dp/verify-orders' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/approve-account' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/create-market-order' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/designated-report' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/display-time' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/dispute-contribute' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/do-initial-report' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/do-market-contribute' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/escape-hatch' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/fill-market-orders' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/finalize-market' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/force-dispute' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/force-finalize' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/fork' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/get-balance' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/get-market-balance' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/get-payout-numerators' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/get-rep-tokens' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/get-timestamp' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/go-to-fork' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/index' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/initial-report' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/list-market-orders' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/list-markets' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/market-info' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/push-time' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/push-timestamp' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/set-timestamp-cmd' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/set-timestamp' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/show-initial-reporter' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/trade-complete-sets' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/flash/transfer-assets' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/get-version' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/helpers/claim-proceeds' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/helpers/create-spread-orders' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/helpers/extract-priv-key' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/helpers/fill-market-order' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/merge-json-files' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/rep-faucet' {
  declare module.exports: any;
}

declare module 'augur.js/scripts/test-pause-unpause-rep' {
  declare module.exports: any;
}

declare module 'augur.js/src/accounts/approve-augur' {
  declare module.exports: any;
}

declare module 'augur.js/src/accounts/get-account-transfer-history' {
  declare module.exports: any;
}

declare module 'augur.js/src/accounts/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/api/bind-contract-function' {
  declare module.exports: any;
}

declare module 'augur.js/src/api/encode-transaction-inputs' {
  declare module.exports: any;
}

declare module 'augur.js/src/api/generate-contract-api' {
  declare module.exports: any;
}

declare module 'augur.js/src/api/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/api/transaction-input-encoders' {
  declare module.exports: any;
}

declare module 'augur.js/src/assets/deposit-ether' {
  declare module.exports: any;
}

declare module 'augur.js/src/assets/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/assets/send-ether' {
  declare module.exports: any;
}

declare module 'augur.js/src/assets/send-reputation' {
  declare module.exports: any;
}

declare module 'augur.js/src/augur-node/connect' {
  declare module.exports: any;
}

declare module 'augur.js/src/augur-node/dispatch-json-rpc-response' {
  declare module.exports: any;
}

declare module 'augur.js/src/augur-node/get-sync-data' {
  declare module.exports: any;
}

declare module 'augur.js/src/augur-node/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/augur-node/state' {
  declare module.exports: any;
}

declare module 'augur.js/src/augur-node/submit-json-rpc-request' {
  declare module.exports: any;
}

declare module 'augur.js/src/augur-node/subscribe-to-event' {
  declare module.exports: any;
}

declare module 'augur.js/src/augur-node/unsubscribe-from-all-events' {
  declare module.exports: any;
}

declare module 'augur.js/src/augur-node/unsubscribe-from-event' {
  declare module.exports: any;
}

declare module 'augur.js/src/connect/connect-to-ethereum' {
  declare module.exports: any;
}

declare module 'augur.js/src/connect/create-configuration' {
  declare module.exports: any;
}

declare module 'augur.js/src/connect/create-ethrpc-configuration' {
  declare module.exports: any;
}

declare module 'augur.js/src/connect/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/connect/set-contracts' {
  declare module.exports: any;
}

declare module 'augur.js/src/connect/set-from' {
  declare module.exports: any;
}

declare module 'augur.js/src/connect/setup-events-abi' {
  declare module.exports: any;
}

declare module 'augur.js/src/connect/setup-functions-abi' {
  declare module.exports: any;
}

declare module 'augur.js/src/constants' {
  declare module.exports: any;
}

declare module 'augur.js/src/contracts/generate-abi-map' {
  declare module.exports: any;
}

declare module 'augur.js/src/contracts/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/create-market/calculate-num-ticks' {
  declare module.exports: any;
}

declare module 'augur.js/src/create-market/create-categorical-market' {
  declare module.exports: any;
}

declare module 'augur.js/src/create-market/create-scalar-market' {
  declare module.exports: any;
}

declare module 'augur.js/src/create-market/create-yes-no-market' {
  declare module.exports: any;
}

declare module 'augur.js/src/create-market/get-market-creation-cost-breakdown' {
  declare module.exports: any;
}

declare module 'augur.js/src/create-market/get-market-creation-cost' {
  declare module.exports: any;
}

declare module 'augur.js/src/create-market/get-market-from-create-market-receipt' {
  declare module.exports: any;
}

declare module 'augur.js/src/create-market/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/add-filter' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/build-topics-list' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/find-event-logs-in-log-array' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/get-all-augur-logs' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/get-filtered-logs' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/get-logs' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/hash-event-abi' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/hash-event-signature' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/insert-indexed-log' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/parametrize-filter' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/parse-message/parse-block-message' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/parse-message/parse-log-message' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/process-logs' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/start-augur-node-event-listeners' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/start-block-listeners' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/start-blockchain-event-listeners' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/stop-augur-node-event-listeners' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/stop-block-listeners' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/stop-blockchain-event-listeners' {
  declare module.exports: any;
}

declare module 'augur.js/src/events/subscriptions' {
  declare module.exports: any;
}

declare module 'augur.js/src/format/log/format-log-message' {
  declare module.exports: any;
}

declare module 'augur.js/src/format/log/format-logged-event-inputs' {
  declare module.exports: any;
}

declare module 'augur.js/src/format/log/format-logged-event-topic' {
  declare module.exports: any;
}

declare module 'augur.js/src/format/log/format-trade-type' {
  declare module.exports: any;
}

declare module 'augur.js/src/format/log/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/format/tag/decode-tag' {
  declare module.exports: any;
}

declare module 'augur.js/src/format/tag/encode-tag-array' {
  declare module.exports: any;
}

declare module 'augur.js/src/format/tag/encode-tag' {
  declare module.exports: any;
}

declare module 'augur.js/src/format/tag/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/markets/get-categories' {
  declare module.exports: any;
}

declare module 'augur.js/src/markets/get-market-price-history' {
  declare module.exports: any;
}

declare module 'augur.js/src/markets/get-markets-closing-in-date-range' {
  declare module.exports: any;
}

declare module 'augur.js/src/markets/get-markets-created-by-user' {
  declare module.exports: any;
}

declare module 'augur.js/src/markets/get-markets-in-category' {
  declare module.exports: any;
}

declare module 'augur.js/src/markets/get-markets-info' {
  declare module.exports: any;
}

declare module 'augur.js/src/markets/get-markets' {
  declare module.exports: any;
}

declare module 'augur.js/src/markets/get-unclaimed-market-creator-fees' {
  declare module.exports: any;
}

declare module 'augur.js/src/markets/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/reporting/claim-reporting-fees-forked-market' {
  declare module.exports: any;
}

declare module 'augur.js/src/reporting/claim-reporting-fees-nonforked-markets' {
  declare module.exports: any;
}

declare module 'augur.js/src/reporting/finalize-market' {
  declare module.exports: any;
}

declare module 'augur.js/src/reporting/get-current-period-progress' {
  declare module.exports: any;
}

declare module 'augur.js/src/reporting/get-dispute-info' {
  declare module.exports: any;
}

declare module 'augur.js/src/reporting/get-dispute-tokens' {
  declare module.exports: any;
}

declare module 'augur.js/src/reporting/get-fee-window-current' {
  declare module.exports: any;
}

declare module 'augur.js/src/reporting/get-fee-windows' {
  declare module.exports: any;
}

declare module 'augur.js/src/reporting/get-initial-reporters' {
  declare module.exports: any;
}

declare module 'augur.js/src/reporting/get-reporting-fees' {
  declare module.exports: any;
}

declare module 'augur.js/src/reporting/get-reporting-history' {
  declare module.exports: any;
}

declare module 'augur.js/src/reporting/get-reporting-summary' {
  declare module.exports: any;
}

declare module 'augur.js/src/reporting/get-stake-required-for-designated-reporter' {
  declare module.exports: any;
}

declare module 'augur.js/src/reporting/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/rpc-interface' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/calculate-ask-cost' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/calculate-bid-cost' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/calculate-tick-size' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/calculate-trade-cost' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/calculate-trade-gas' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/claim-markets-trading-proceeds' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/claim-trading-proceeds' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/denormalize-price' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/filter-and-sort-by-price' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/generate-trade-group-id' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/get-better-worse-orders' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/get-orders' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/get-position-in-market' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/get-trade-amount-remaining' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/get-user-trading-history' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/get-user-trading-positions' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/normalize-price' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/place-trade' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/profit-loss/calculate-maker-pl' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/profit-loss/calculate-profit-loss' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/profit-loss/calculate-taker-pl' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/profit-loss/calculate-trade-pl' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/profit-loss/calculate-trades-pl' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/profit-loss/calculate-unrealized-pl' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/profit-loss/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/profit-loss/longer-position-pl' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/profit-loss/sell-complete-sets-pl' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/profit-loss/shorter-position-pl' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/profit-loss/update-mean-open-price' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/profit-loss/update-realized-pl' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/simulation/calculate-nearly-complete-sets' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/simulation/calculate-settlement-fee' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/simulation/generate-trade-group-id' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/simulation/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/simulation/modify-other-share-balances' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/simulation/simulate-buy' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/simulation/simulate-create-ask-order' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/simulation/simulate-create-bid-order' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/simulation/simulate-fill-ask-order' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/simulation/simulate-fill-bid-order' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/simulation/simulate-sell' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/simulation/simulate-trade' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/simulation/sum-simulated-results' {
  declare module.exports: any;
}

declare module 'augur.js/src/trading/trade-until-amount-is-zero' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/chunk-blocks' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/convert-big-number-to-hex-string' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/convert-decimal-to-fixed-point' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/convert-display-amount-to-on-chain-amount' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/convert-display-price-to-on-chain-price' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/convert-fixed-point-to-decimal' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/convert-on-chain-amount-to-display-amount' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/convert-on-chain-price-to-display-price' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/index' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/is-function' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/is-object' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/keccak256' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/list-contracts' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/map-contract-addresses-to-names' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/map-event-signatures-to-names' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/noop' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/pass' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/read-json-file' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/sha3' {
  declare module.exports: any;
}

declare module 'augur.js/src/utils/unique' {
  declare module.exports: any;
}

declare module 'augur.js/src/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'augur.js/dist/augur.js' {
  declare module.exports: $Exports<'augur.js/dist/augur'>;
}
declare module 'augur.js/dist/augur.min.js' {
  declare module.exports: $Exports<'augur.js/dist/augur.min'>;
}
declare module 'augur.js/exports.js' {
  declare module.exports: $Exports<'augur.js/exports'>;
}
declare module 'augur.js/scripts/connection-endpoints.js' {
  declare module.exports: $Exports<'augur.js/scripts/connection-endpoints'>;
}
declare module 'augur.js/scripts/core-version.js' {
  declare module.exports: $Exports<'augur.js/scripts/core-version'>;
}
declare module 'augur.js/scripts/decrypt-keystore.js' {
  declare module.exports: $Exports<'augur.js/scripts/decrypt-keystore'>;
}
declare module 'augur.js/scripts/dp/cancel-orders.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/cancel-orders'>;
}
declare module 'augur.js/scripts/dp/create-markets.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/create-markets'>;
}
declare module 'augur.js/scripts/dp/create-orders.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/create-orders'>;
}
declare module 'augur.js/scripts/dp/fill-order.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/fill-order'>;
}
declare module 'augur.js/scripts/dp/fund-accounts.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/fund-accounts'>;
}
declare module 'augur.js/scripts/dp/index.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/index'>;
}
declare module 'augur.js/scripts/dp/lib/approve-augur-eternal-approval-value.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/approve-augur-eternal-approval-value'>;
}
declare module 'augur.js/scripts/dp/lib/cancel-order.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/cancel-order'>;
}
declare module 'augur.js/scripts/dp/lib/cancel-orders.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/cancel-orders'>;
}
declare module 'augur.js/scripts/dp/lib/create-market.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/create-market'>;
}
declare module 'augur.js/scripts/dp/lib/create-markets.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/create-markets'>;
}
declare module 'augur.js/scripts/dp/lib/create-order-book.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/create-order-book'>;
}
declare module 'augur.js/scripts/dp/lib/create-order.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/create-order'>;
}
declare module 'augur.js/scripts/dp/lib/create-orders.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/create-orders'>;
}
declare module 'augur.js/scripts/dp/lib/fill-both-order-types.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/fill-both-order-types'>;
}
declare module 'augur.js/scripts/dp/lib/fill-order.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/fill-order'>;
}
declare module 'augur.js/scripts/dp/lib/fund-accounts.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/fund-accounts'>;
}
declare module 'augur.js/scripts/dp/lib/get-balances.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/get-balances'>;
}
declare module 'augur.js/scripts/dp/lib/get-order-to-fill.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/get-order-to-fill'>;
}
declare module 'augur.js/scripts/dp/lib/get-private-key.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/get-private-key'>;
}
declare module 'augur.js/scripts/dp/lib/print-transaction-status.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/print-transaction-status'>;
}
declare module 'augur.js/scripts/dp/lib/select-canned-market.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/select-canned-market'>;
}
declare module 'augur.js/scripts/dp/lib/verify-order-book.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/lib/verify-order-book'>;
}
declare module 'augur.js/scripts/dp/verify-orders.js' {
  declare module.exports: $Exports<'augur.js/scripts/dp/verify-orders'>;
}
declare module 'augur.js/scripts/flash/approve-account.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/approve-account'>;
}
declare module 'augur.js/scripts/flash/create-market-order.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/create-market-order'>;
}
declare module 'augur.js/scripts/flash/designated-report.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/designated-report'>;
}
declare module 'augur.js/scripts/flash/display-time.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/display-time'>;
}
declare module 'augur.js/scripts/flash/dispute-contribute.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/dispute-contribute'>;
}
declare module 'augur.js/scripts/flash/do-initial-report.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/do-initial-report'>;
}
declare module 'augur.js/scripts/flash/do-market-contribute.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/do-market-contribute'>;
}
declare module 'augur.js/scripts/flash/escape-hatch.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/escape-hatch'>;
}
declare module 'augur.js/scripts/flash/fill-market-orders.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/fill-market-orders'>;
}
declare module 'augur.js/scripts/flash/finalize-market.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/finalize-market'>;
}
declare module 'augur.js/scripts/flash/force-dispute.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/force-dispute'>;
}
declare module 'augur.js/scripts/flash/force-finalize.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/force-finalize'>;
}
declare module 'augur.js/scripts/flash/fork.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/fork'>;
}
declare module 'augur.js/scripts/flash/get-balance.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/get-balance'>;
}
declare module 'augur.js/scripts/flash/get-market-balance.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/get-market-balance'>;
}
declare module 'augur.js/scripts/flash/get-payout-numerators.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/get-payout-numerators'>;
}
declare module 'augur.js/scripts/flash/get-rep-tokens.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/get-rep-tokens'>;
}
declare module 'augur.js/scripts/flash/get-timestamp.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/get-timestamp'>;
}
declare module 'augur.js/scripts/flash/go-to-fork.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/go-to-fork'>;
}
declare module 'augur.js/scripts/flash/index.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/index'>;
}
declare module 'augur.js/scripts/flash/initial-report.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/initial-report'>;
}
declare module 'augur.js/scripts/flash/list-market-orders.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/list-market-orders'>;
}
declare module 'augur.js/scripts/flash/list-markets.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/list-markets'>;
}
declare module 'augur.js/scripts/flash/market-info.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/market-info'>;
}
declare module 'augur.js/scripts/flash/push-time.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/push-time'>;
}
declare module 'augur.js/scripts/flash/push-timestamp.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/push-timestamp'>;
}
declare module 'augur.js/scripts/flash/set-timestamp-cmd.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/set-timestamp-cmd'>;
}
declare module 'augur.js/scripts/flash/set-timestamp.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/set-timestamp'>;
}
declare module 'augur.js/scripts/flash/show-initial-reporter.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/show-initial-reporter'>;
}
declare module 'augur.js/scripts/flash/trade-complete-sets.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/trade-complete-sets'>;
}
declare module 'augur.js/scripts/flash/transfer-assets.js' {
  declare module.exports: $Exports<'augur.js/scripts/flash/transfer-assets'>;
}
declare module 'augur.js/scripts/get-version.js' {
  declare module.exports: $Exports<'augur.js/scripts/get-version'>;
}
declare module 'augur.js/scripts/helpers/claim-proceeds.js' {
  declare module.exports: $Exports<'augur.js/scripts/helpers/claim-proceeds'>;
}
declare module 'augur.js/scripts/helpers/create-spread-orders.js' {
  declare module.exports: $Exports<'augur.js/scripts/helpers/create-spread-orders'>;
}
declare module 'augur.js/scripts/helpers/extract-priv-key.js' {
  declare module.exports: $Exports<'augur.js/scripts/helpers/extract-priv-key'>;
}
declare module 'augur.js/scripts/helpers/fill-market-order.js' {
  declare module.exports: $Exports<'augur.js/scripts/helpers/fill-market-order'>;
}
declare module 'augur.js/scripts/merge-json-files.js' {
  declare module.exports: $Exports<'augur.js/scripts/merge-json-files'>;
}
declare module 'augur.js/scripts/rep-faucet.js' {
  declare module.exports: $Exports<'augur.js/scripts/rep-faucet'>;
}
declare module 'augur.js/scripts/test-pause-unpause-rep.js' {
  declare module.exports: $Exports<'augur.js/scripts/test-pause-unpause-rep'>;
}
declare module 'augur.js/src/accounts/approve-augur.js' {
  declare module.exports: $Exports<'augur.js/src/accounts/approve-augur'>;
}
declare module 'augur.js/src/accounts/get-account-transfer-history.js' {
  declare module.exports: $Exports<'augur.js/src/accounts/get-account-transfer-history'>;
}
declare module 'augur.js/src/accounts/index.js' {
  declare module.exports: $Exports<'augur.js/src/accounts/index'>;
}
declare module 'augur.js/src/api/bind-contract-function.js' {
  declare module.exports: $Exports<'augur.js/src/api/bind-contract-function'>;
}
declare module 'augur.js/src/api/encode-transaction-inputs.js' {
  declare module.exports: $Exports<'augur.js/src/api/encode-transaction-inputs'>;
}
declare module 'augur.js/src/api/generate-contract-api.js' {
  declare module.exports: $Exports<'augur.js/src/api/generate-contract-api'>;
}
declare module 'augur.js/src/api/index.js' {
  declare module.exports: $Exports<'augur.js/src/api/index'>;
}
declare module 'augur.js/src/api/transaction-input-encoders.js' {
  declare module.exports: $Exports<'augur.js/src/api/transaction-input-encoders'>;
}
declare module 'augur.js/src/assets/deposit-ether.js' {
  declare module.exports: $Exports<'augur.js/src/assets/deposit-ether'>;
}
declare module 'augur.js/src/assets/index.js' {
  declare module.exports: $Exports<'augur.js/src/assets/index'>;
}
declare module 'augur.js/src/assets/send-ether.js' {
  declare module.exports: $Exports<'augur.js/src/assets/send-ether'>;
}
declare module 'augur.js/src/assets/send-reputation.js' {
  declare module.exports: $Exports<'augur.js/src/assets/send-reputation'>;
}
declare module 'augur.js/src/augur-node/connect.js' {
  declare module.exports: $Exports<'augur.js/src/augur-node/connect'>;
}
declare module 'augur.js/src/augur-node/dispatch-json-rpc-response.js' {
  declare module.exports: $Exports<'augur.js/src/augur-node/dispatch-json-rpc-response'>;
}
declare module 'augur.js/src/augur-node/get-sync-data.js' {
  declare module.exports: $Exports<'augur.js/src/augur-node/get-sync-data'>;
}
declare module 'augur.js/src/augur-node/index.js' {
  declare module.exports: $Exports<'augur.js/src/augur-node/index'>;
}
declare module 'augur.js/src/augur-node/state.js' {
  declare module.exports: $Exports<'augur.js/src/augur-node/state'>;
}
declare module 'augur.js/src/augur-node/submit-json-rpc-request.js' {
  declare module.exports: $Exports<'augur.js/src/augur-node/submit-json-rpc-request'>;
}
declare module 'augur.js/src/augur-node/subscribe-to-event.js' {
  declare module.exports: $Exports<'augur.js/src/augur-node/subscribe-to-event'>;
}
declare module 'augur.js/src/augur-node/unsubscribe-from-all-events.js' {
  declare module.exports: $Exports<'augur.js/src/augur-node/unsubscribe-from-all-events'>;
}
declare module 'augur.js/src/augur-node/unsubscribe-from-event.js' {
  declare module.exports: $Exports<'augur.js/src/augur-node/unsubscribe-from-event'>;
}
declare module 'augur.js/src/connect/connect-to-ethereum.js' {
  declare module.exports: $Exports<'augur.js/src/connect/connect-to-ethereum'>;
}
declare module 'augur.js/src/connect/create-configuration.js' {
  declare module.exports: $Exports<'augur.js/src/connect/create-configuration'>;
}
declare module 'augur.js/src/connect/create-ethrpc-configuration.js' {
  declare module.exports: $Exports<'augur.js/src/connect/create-ethrpc-configuration'>;
}
declare module 'augur.js/src/connect/index.js' {
  declare module.exports: $Exports<'augur.js/src/connect/index'>;
}
declare module 'augur.js/src/connect/set-contracts.js' {
  declare module.exports: $Exports<'augur.js/src/connect/set-contracts'>;
}
declare module 'augur.js/src/connect/set-from.js' {
  declare module.exports: $Exports<'augur.js/src/connect/set-from'>;
}
declare module 'augur.js/src/connect/setup-events-abi.js' {
  declare module.exports: $Exports<'augur.js/src/connect/setup-events-abi'>;
}
declare module 'augur.js/src/connect/setup-functions-abi.js' {
  declare module.exports: $Exports<'augur.js/src/connect/setup-functions-abi'>;
}
declare module 'augur.js/src/constants.js' {
  declare module.exports: $Exports<'augur.js/src/constants'>;
}
declare module 'augur.js/src/contracts/generate-abi-map.js' {
  declare module.exports: $Exports<'augur.js/src/contracts/generate-abi-map'>;
}
declare module 'augur.js/src/contracts/index.js' {
  declare module.exports: $Exports<'augur.js/src/contracts/index'>;
}
declare module 'augur.js/src/create-market/calculate-num-ticks.js' {
  declare module.exports: $Exports<'augur.js/src/create-market/calculate-num-ticks'>;
}
declare module 'augur.js/src/create-market/create-categorical-market.js' {
  declare module.exports: $Exports<'augur.js/src/create-market/create-categorical-market'>;
}
declare module 'augur.js/src/create-market/create-scalar-market.js' {
  declare module.exports: $Exports<'augur.js/src/create-market/create-scalar-market'>;
}
declare module 'augur.js/src/create-market/create-yes-no-market.js' {
  declare module.exports: $Exports<'augur.js/src/create-market/create-yes-no-market'>;
}
declare module 'augur.js/src/create-market/get-market-creation-cost-breakdown.js' {
  declare module.exports: $Exports<'augur.js/src/create-market/get-market-creation-cost-breakdown'>;
}
declare module 'augur.js/src/create-market/get-market-creation-cost.js' {
  declare module.exports: $Exports<'augur.js/src/create-market/get-market-creation-cost'>;
}
declare module 'augur.js/src/create-market/get-market-from-create-market-receipt.js' {
  declare module.exports: $Exports<'augur.js/src/create-market/get-market-from-create-market-receipt'>;
}
declare module 'augur.js/src/create-market/index.js' {
  declare module.exports: $Exports<'augur.js/src/create-market/index'>;
}
declare module 'augur.js/src/events/add-filter.js' {
  declare module.exports: $Exports<'augur.js/src/events/add-filter'>;
}
declare module 'augur.js/src/events/build-topics-list.js' {
  declare module.exports: $Exports<'augur.js/src/events/build-topics-list'>;
}
declare module 'augur.js/src/events/find-event-logs-in-log-array.js' {
  declare module.exports: $Exports<'augur.js/src/events/find-event-logs-in-log-array'>;
}
declare module 'augur.js/src/events/get-all-augur-logs.js' {
  declare module.exports: $Exports<'augur.js/src/events/get-all-augur-logs'>;
}
declare module 'augur.js/src/events/get-filtered-logs.js' {
  declare module.exports: $Exports<'augur.js/src/events/get-filtered-logs'>;
}
declare module 'augur.js/src/events/get-logs.js' {
  declare module.exports: $Exports<'augur.js/src/events/get-logs'>;
}
declare module 'augur.js/src/events/hash-event-abi.js' {
  declare module.exports: $Exports<'augur.js/src/events/hash-event-abi'>;
}
declare module 'augur.js/src/events/hash-event-signature.js' {
  declare module.exports: $Exports<'augur.js/src/events/hash-event-signature'>;
}
declare module 'augur.js/src/events/index.js' {
  declare module.exports: $Exports<'augur.js/src/events/index'>;
}
declare module 'augur.js/src/events/insert-indexed-log.js' {
  declare module.exports: $Exports<'augur.js/src/events/insert-indexed-log'>;
}
declare module 'augur.js/src/events/parametrize-filter.js' {
  declare module.exports: $Exports<'augur.js/src/events/parametrize-filter'>;
}
declare module 'augur.js/src/events/parse-message/parse-block-message.js' {
  declare module.exports: $Exports<'augur.js/src/events/parse-message/parse-block-message'>;
}
declare module 'augur.js/src/events/parse-message/parse-log-message.js' {
  declare module.exports: $Exports<'augur.js/src/events/parse-message/parse-log-message'>;
}
declare module 'augur.js/src/events/process-logs.js' {
  declare module.exports: $Exports<'augur.js/src/events/process-logs'>;
}
declare module 'augur.js/src/events/start-augur-node-event-listeners.js' {
  declare module.exports: $Exports<'augur.js/src/events/start-augur-node-event-listeners'>;
}
declare module 'augur.js/src/events/start-block-listeners.js' {
  declare module.exports: $Exports<'augur.js/src/events/start-block-listeners'>;
}
declare module 'augur.js/src/events/start-blockchain-event-listeners.js' {
  declare module.exports: $Exports<'augur.js/src/events/start-blockchain-event-listeners'>;
}
declare module 'augur.js/src/events/stop-augur-node-event-listeners.js' {
  declare module.exports: $Exports<'augur.js/src/events/stop-augur-node-event-listeners'>;
}
declare module 'augur.js/src/events/stop-block-listeners.js' {
  declare module.exports: $Exports<'augur.js/src/events/stop-block-listeners'>;
}
declare module 'augur.js/src/events/stop-blockchain-event-listeners.js' {
  declare module.exports: $Exports<'augur.js/src/events/stop-blockchain-event-listeners'>;
}
declare module 'augur.js/src/events/subscriptions.js' {
  declare module.exports: $Exports<'augur.js/src/events/subscriptions'>;
}
declare module 'augur.js/src/format/log/format-log-message.js' {
  declare module.exports: $Exports<'augur.js/src/format/log/format-log-message'>;
}
declare module 'augur.js/src/format/log/format-logged-event-inputs.js' {
  declare module.exports: $Exports<'augur.js/src/format/log/format-logged-event-inputs'>;
}
declare module 'augur.js/src/format/log/format-logged-event-topic.js' {
  declare module.exports: $Exports<'augur.js/src/format/log/format-logged-event-topic'>;
}
declare module 'augur.js/src/format/log/format-trade-type.js' {
  declare module.exports: $Exports<'augur.js/src/format/log/format-trade-type'>;
}
declare module 'augur.js/src/format/log/index.js' {
  declare module.exports: $Exports<'augur.js/src/format/log/index'>;
}
declare module 'augur.js/src/format/tag/decode-tag.js' {
  declare module.exports: $Exports<'augur.js/src/format/tag/decode-tag'>;
}
declare module 'augur.js/src/format/tag/encode-tag-array.js' {
  declare module.exports: $Exports<'augur.js/src/format/tag/encode-tag-array'>;
}
declare module 'augur.js/src/format/tag/encode-tag.js' {
  declare module.exports: $Exports<'augur.js/src/format/tag/encode-tag'>;
}
declare module 'augur.js/src/format/tag/index.js' {
  declare module.exports: $Exports<'augur.js/src/format/tag/index'>;
}
declare module 'augur.js/src/index.js' {
  declare module.exports: $Exports<'augur.js/src/index'>;
}
declare module 'augur.js/src/markets/get-categories.js' {
  declare module.exports: $Exports<'augur.js/src/markets/get-categories'>;
}
declare module 'augur.js/src/markets/get-market-price-history.js' {
  declare module.exports: $Exports<'augur.js/src/markets/get-market-price-history'>;
}
declare module 'augur.js/src/markets/get-markets-closing-in-date-range.js' {
  declare module.exports: $Exports<'augur.js/src/markets/get-markets-closing-in-date-range'>;
}
declare module 'augur.js/src/markets/get-markets-created-by-user.js' {
  declare module.exports: $Exports<'augur.js/src/markets/get-markets-created-by-user'>;
}
declare module 'augur.js/src/markets/get-markets-in-category.js' {
  declare module.exports: $Exports<'augur.js/src/markets/get-markets-in-category'>;
}
declare module 'augur.js/src/markets/get-markets-info.js' {
  declare module.exports: $Exports<'augur.js/src/markets/get-markets-info'>;
}
declare module 'augur.js/src/markets/get-markets.js' {
  declare module.exports: $Exports<'augur.js/src/markets/get-markets'>;
}
declare module 'augur.js/src/markets/get-unclaimed-market-creator-fees.js' {
  declare module.exports: $Exports<'augur.js/src/markets/get-unclaimed-market-creator-fees'>;
}
declare module 'augur.js/src/markets/index.js' {
  declare module.exports: $Exports<'augur.js/src/markets/index'>;
}
declare module 'augur.js/src/reporting/claim-reporting-fees-forked-market.js' {
  declare module.exports: $Exports<'augur.js/src/reporting/claim-reporting-fees-forked-market'>;
}
declare module 'augur.js/src/reporting/claim-reporting-fees-nonforked-markets.js' {
  declare module.exports: $Exports<'augur.js/src/reporting/claim-reporting-fees-nonforked-markets'>;
}
declare module 'augur.js/src/reporting/finalize-market.js' {
  declare module.exports: $Exports<'augur.js/src/reporting/finalize-market'>;
}
declare module 'augur.js/src/reporting/get-current-period-progress.js' {
  declare module.exports: $Exports<'augur.js/src/reporting/get-current-period-progress'>;
}
declare module 'augur.js/src/reporting/get-dispute-info.js' {
  declare module.exports: $Exports<'augur.js/src/reporting/get-dispute-info'>;
}
declare module 'augur.js/src/reporting/get-dispute-tokens.js' {
  declare module.exports: $Exports<'augur.js/src/reporting/get-dispute-tokens'>;
}
declare module 'augur.js/src/reporting/get-fee-window-current.js' {
  declare module.exports: $Exports<'augur.js/src/reporting/get-fee-window-current'>;
}
declare module 'augur.js/src/reporting/get-fee-windows.js' {
  declare module.exports: $Exports<'augur.js/src/reporting/get-fee-windows'>;
}
declare module 'augur.js/src/reporting/get-initial-reporters.js' {
  declare module.exports: $Exports<'augur.js/src/reporting/get-initial-reporters'>;
}
declare module 'augur.js/src/reporting/get-reporting-fees.js' {
  declare module.exports: $Exports<'augur.js/src/reporting/get-reporting-fees'>;
}
declare module 'augur.js/src/reporting/get-reporting-history.js' {
  declare module.exports: $Exports<'augur.js/src/reporting/get-reporting-history'>;
}
declare module 'augur.js/src/reporting/get-reporting-summary.js' {
  declare module.exports: $Exports<'augur.js/src/reporting/get-reporting-summary'>;
}
declare module 'augur.js/src/reporting/get-stake-required-for-designated-reporter.js' {
  declare module.exports: $Exports<'augur.js/src/reporting/get-stake-required-for-designated-reporter'>;
}
declare module 'augur.js/src/reporting/index.js' {
  declare module.exports: $Exports<'augur.js/src/reporting/index'>;
}
declare module 'augur.js/src/rpc-interface.js' {
  declare module.exports: $Exports<'augur.js/src/rpc-interface'>;
}
declare module 'augur.js/src/trading/calculate-ask-cost.js' {
  declare module.exports: $Exports<'augur.js/src/trading/calculate-ask-cost'>;
}
declare module 'augur.js/src/trading/calculate-bid-cost.js' {
  declare module.exports: $Exports<'augur.js/src/trading/calculate-bid-cost'>;
}
declare module 'augur.js/src/trading/calculate-tick-size.js' {
  declare module.exports: $Exports<'augur.js/src/trading/calculate-tick-size'>;
}
declare module 'augur.js/src/trading/calculate-trade-cost.js' {
  declare module.exports: $Exports<'augur.js/src/trading/calculate-trade-cost'>;
}
declare module 'augur.js/src/trading/calculate-trade-gas.js' {
  declare module.exports: $Exports<'augur.js/src/trading/calculate-trade-gas'>;
}
declare module 'augur.js/src/trading/claim-markets-trading-proceeds.js' {
  declare module.exports: $Exports<'augur.js/src/trading/claim-markets-trading-proceeds'>;
}
declare module 'augur.js/src/trading/claim-trading-proceeds.js' {
  declare module.exports: $Exports<'augur.js/src/trading/claim-trading-proceeds'>;
}
declare module 'augur.js/src/trading/denormalize-price.js' {
  declare module.exports: $Exports<'augur.js/src/trading/denormalize-price'>;
}
declare module 'augur.js/src/trading/filter-and-sort-by-price.js' {
  declare module.exports: $Exports<'augur.js/src/trading/filter-and-sort-by-price'>;
}
declare module 'augur.js/src/trading/generate-trade-group-id.js' {
  declare module.exports: $Exports<'augur.js/src/trading/generate-trade-group-id'>;
}
declare module 'augur.js/src/trading/get-better-worse-orders.js' {
  declare module.exports: $Exports<'augur.js/src/trading/get-better-worse-orders'>;
}
declare module 'augur.js/src/trading/get-orders.js' {
  declare module.exports: $Exports<'augur.js/src/trading/get-orders'>;
}
declare module 'augur.js/src/trading/get-position-in-market.js' {
  declare module.exports: $Exports<'augur.js/src/trading/get-position-in-market'>;
}
declare module 'augur.js/src/trading/get-trade-amount-remaining.js' {
  declare module.exports: $Exports<'augur.js/src/trading/get-trade-amount-remaining'>;
}
declare module 'augur.js/src/trading/get-user-trading-history.js' {
  declare module.exports: $Exports<'augur.js/src/trading/get-user-trading-history'>;
}
declare module 'augur.js/src/trading/get-user-trading-positions.js' {
  declare module.exports: $Exports<'augur.js/src/trading/get-user-trading-positions'>;
}
declare module 'augur.js/src/trading/index.js' {
  declare module.exports: $Exports<'augur.js/src/trading/index'>;
}
declare module 'augur.js/src/trading/normalize-price.js' {
  declare module.exports: $Exports<'augur.js/src/trading/normalize-price'>;
}
declare module 'augur.js/src/trading/place-trade.js' {
  declare module.exports: $Exports<'augur.js/src/trading/place-trade'>;
}
declare module 'augur.js/src/trading/profit-loss/calculate-maker-pl.js' {
  declare module.exports: $Exports<'augur.js/src/trading/profit-loss/calculate-maker-pl'>;
}
declare module 'augur.js/src/trading/profit-loss/calculate-profit-loss.js' {
  declare module.exports: $Exports<'augur.js/src/trading/profit-loss/calculate-profit-loss'>;
}
declare module 'augur.js/src/trading/profit-loss/calculate-taker-pl.js' {
  declare module.exports: $Exports<'augur.js/src/trading/profit-loss/calculate-taker-pl'>;
}
declare module 'augur.js/src/trading/profit-loss/calculate-trade-pl.js' {
  declare module.exports: $Exports<'augur.js/src/trading/profit-loss/calculate-trade-pl'>;
}
declare module 'augur.js/src/trading/profit-loss/calculate-trades-pl.js' {
  declare module.exports: $Exports<'augur.js/src/trading/profit-loss/calculate-trades-pl'>;
}
declare module 'augur.js/src/trading/profit-loss/calculate-unrealized-pl.js' {
  declare module.exports: $Exports<'augur.js/src/trading/profit-loss/calculate-unrealized-pl'>;
}
declare module 'augur.js/src/trading/profit-loss/index.js' {
  declare module.exports: $Exports<'augur.js/src/trading/profit-loss/index'>;
}
declare module 'augur.js/src/trading/profit-loss/longer-position-pl.js' {
  declare module.exports: $Exports<'augur.js/src/trading/profit-loss/longer-position-pl'>;
}
declare module 'augur.js/src/trading/profit-loss/sell-complete-sets-pl.js' {
  declare module.exports: $Exports<'augur.js/src/trading/profit-loss/sell-complete-sets-pl'>;
}
declare module 'augur.js/src/trading/profit-loss/shorter-position-pl.js' {
  declare module.exports: $Exports<'augur.js/src/trading/profit-loss/shorter-position-pl'>;
}
declare module 'augur.js/src/trading/profit-loss/update-mean-open-price.js' {
  declare module.exports: $Exports<'augur.js/src/trading/profit-loss/update-mean-open-price'>;
}
declare module 'augur.js/src/trading/profit-loss/update-realized-pl.js' {
  declare module.exports: $Exports<'augur.js/src/trading/profit-loss/update-realized-pl'>;
}
declare module 'augur.js/src/trading/simulation/calculate-nearly-complete-sets.js' {
  declare module.exports: $Exports<'augur.js/src/trading/simulation/calculate-nearly-complete-sets'>;
}
declare module 'augur.js/src/trading/simulation/calculate-settlement-fee.js' {
  declare module.exports: $Exports<'augur.js/src/trading/simulation/calculate-settlement-fee'>;
}
declare module 'augur.js/src/trading/simulation/generate-trade-group-id.js' {
  declare module.exports: $Exports<'augur.js/src/trading/simulation/generate-trade-group-id'>;
}
declare module 'augur.js/src/trading/simulation/index.js' {
  declare module.exports: $Exports<'augur.js/src/trading/simulation/index'>;
}
declare module 'augur.js/src/trading/simulation/modify-other-share-balances.js' {
  declare module.exports: $Exports<'augur.js/src/trading/simulation/modify-other-share-balances'>;
}
declare module 'augur.js/src/trading/simulation/simulate-buy.js' {
  declare module.exports: $Exports<'augur.js/src/trading/simulation/simulate-buy'>;
}
declare module 'augur.js/src/trading/simulation/simulate-create-ask-order.js' {
  declare module.exports: $Exports<'augur.js/src/trading/simulation/simulate-create-ask-order'>;
}
declare module 'augur.js/src/trading/simulation/simulate-create-bid-order.js' {
  declare module.exports: $Exports<'augur.js/src/trading/simulation/simulate-create-bid-order'>;
}
declare module 'augur.js/src/trading/simulation/simulate-fill-ask-order.js' {
  declare module.exports: $Exports<'augur.js/src/trading/simulation/simulate-fill-ask-order'>;
}
declare module 'augur.js/src/trading/simulation/simulate-fill-bid-order.js' {
  declare module.exports: $Exports<'augur.js/src/trading/simulation/simulate-fill-bid-order'>;
}
declare module 'augur.js/src/trading/simulation/simulate-sell.js' {
  declare module.exports: $Exports<'augur.js/src/trading/simulation/simulate-sell'>;
}
declare module 'augur.js/src/trading/simulation/simulate-trade.js' {
  declare module.exports: $Exports<'augur.js/src/trading/simulation/simulate-trade'>;
}
declare module 'augur.js/src/trading/simulation/sum-simulated-results.js' {
  declare module.exports: $Exports<'augur.js/src/trading/simulation/sum-simulated-results'>;
}
declare module 'augur.js/src/trading/trade-until-amount-is-zero.js' {
  declare module.exports: $Exports<'augur.js/src/trading/trade-until-amount-is-zero'>;
}
declare module 'augur.js/src/utils/chunk-blocks.js' {
  declare module.exports: $Exports<'augur.js/src/utils/chunk-blocks'>;
}
declare module 'augur.js/src/utils/convert-big-number-to-hex-string.js' {
  declare module.exports: $Exports<'augur.js/src/utils/convert-big-number-to-hex-string'>;
}
declare module 'augur.js/src/utils/convert-decimal-to-fixed-point.js' {
  declare module.exports: $Exports<'augur.js/src/utils/convert-decimal-to-fixed-point'>;
}
declare module 'augur.js/src/utils/convert-display-amount-to-on-chain-amount.js' {
  declare module.exports: $Exports<'augur.js/src/utils/convert-display-amount-to-on-chain-amount'>;
}
declare module 'augur.js/src/utils/convert-display-price-to-on-chain-price.js' {
  declare module.exports: $Exports<'augur.js/src/utils/convert-display-price-to-on-chain-price'>;
}
declare module 'augur.js/src/utils/convert-fixed-point-to-decimal.js' {
  declare module.exports: $Exports<'augur.js/src/utils/convert-fixed-point-to-decimal'>;
}
declare module 'augur.js/src/utils/convert-on-chain-amount-to-display-amount.js' {
  declare module.exports: $Exports<'augur.js/src/utils/convert-on-chain-amount-to-display-amount'>;
}
declare module 'augur.js/src/utils/convert-on-chain-price-to-display-price.js' {
  declare module.exports: $Exports<'augur.js/src/utils/convert-on-chain-price-to-display-price'>;
}
declare module 'augur.js/src/utils/index.js' {
  declare module.exports: $Exports<'augur.js/src/utils/index'>;
}
declare module 'augur.js/src/utils/is-function.js' {
  declare module.exports: $Exports<'augur.js/src/utils/is-function'>;
}
declare module 'augur.js/src/utils/is-object.js' {
  declare module.exports: $Exports<'augur.js/src/utils/is-object'>;
}
declare module 'augur.js/src/utils/keccak256.js' {
  declare module.exports: $Exports<'augur.js/src/utils/keccak256'>;
}
declare module 'augur.js/src/utils/list-contracts.js' {
  declare module.exports: $Exports<'augur.js/src/utils/list-contracts'>;
}
declare module 'augur.js/src/utils/map-contract-addresses-to-names.js' {
  declare module.exports: $Exports<'augur.js/src/utils/map-contract-addresses-to-names'>;
}
declare module 'augur.js/src/utils/map-event-signatures-to-names.js' {
  declare module.exports: $Exports<'augur.js/src/utils/map-event-signatures-to-names'>;
}
declare module 'augur.js/src/utils/noop.js' {
  declare module.exports: $Exports<'augur.js/src/utils/noop'>;
}
declare module 'augur.js/src/utils/pass.js' {
  declare module.exports: $Exports<'augur.js/src/utils/pass'>;
}
declare module 'augur.js/src/utils/read-json-file.js' {
  declare module.exports: $Exports<'augur.js/src/utils/read-json-file'>;
}
declare module 'augur.js/src/utils/sha3.js' {
  declare module.exports: $Exports<'augur.js/src/utils/sha3'>;
}
declare module 'augur.js/src/utils/unique.js' {
  declare module.exports: $Exports<'augur.js/src/utils/unique'>;
}
declare module 'augur.js/src/version.js' {
  declare module.exports: $Exports<'augur.js/src/version'>;
}
