// flow-typed signature: ec80927bbd2f42f5c0b37cf5c8208e81
// flow-typed version: <<STUB>>/speedomatic_v^2.1.4/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'speedomatic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'speedomatic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'speedomatic/exports' {
  declare module.exports: any;
}

declare module 'speedomatic/src/abi-decode-bytes' {
  declare module.exports: any;
}

declare module 'speedomatic/src/abi-decode-data' {
  declare module.exports: any;
}

declare module 'speedomatic/src/abi-decode-rpc-response' {
  declare module.exports: any;
}

declare module 'speedomatic/src/abi-decode-short-string-as-int256' {
  declare module.exports: any;
}

declare module 'speedomatic/src/abi-encode-bytes' {
  declare module.exports: any;
}

declare module 'speedomatic/src/abi-encode-data' {
  declare module.exports: any;
}

declare module 'speedomatic/src/abi-encode-int256' {
  declare module.exports: any;
}

declare module 'speedomatic/src/abi-encode-short-string-as-int256' {
  declare module.exports: any;
}

declare module 'speedomatic/src/abi-encode-transaction-payload' {
  declare module.exports: any;
}

declare module 'speedomatic/src/bignum' {
  declare module.exports: any;
}

declare module 'speedomatic/src/byte-array-to-hex-string' {
  declare module.exports: any;
}

declare module 'speedomatic/src/byte-array-to-utf8-string' {
  declare module.exports: any;
}

declare module 'speedomatic/src/chunk' {
  declare module.exports: any;
}

declare module 'speedomatic/src/constants' {
  declare module.exports: any;
}

declare module 'speedomatic/src/encode-number-as-base10-string' {
  declare module.exports: any;
}

declare module 'speedomatic/src/encode-number-as-js-number' {
  declare module.exports: any;
}

declare module 'speedomatic/src/fix' {
  declare module.exports: any;
}

declare module 'speedomatic/src/format-abi-raw-decoded-data-array' {
  declare module.exports: any;
}

declare module 'speedomatic/src/format-abi-raw-decoded-data' {
  declare module.exports: any;
}

declare module 'speedomatic/src/format-ethereum-address' {
  declare module.exports: any;
}

declare module 'speedomatic/src/format-int256' {
  declare module.exports: any;
}

declare module 'speedomatic/src/hex' {
  declare module.exports: any;
}

declare module 'speedomatic/src/index' {
  declare module.exports: any;
}

declare module 'speedomatic/src/is-hex' {
  declare module.exports: any;
}

declare module 'speedomatic/src/pad-left' {
  declare module.exports: any;
}

declare module 'speedomatic/src/pad-right' {
  declare module.exports: any;
}

declare module 'speedomatic/src/prefix-hex' {
  declare module.exports: any;
}

declare module 'speedomatic/src/remove-trailing-zeros' {
  declare module.exports: any;
}

declare module 'speedomatic/src/serialize' {
  declare module.exports: any;
}

declare module 'speedomatic/src/strip-0x-prefix' {
  declare module.exports: any;
}

declare module 'speedomatic/src/unfix-signed' {
  declare module.exports: any;
}

declare module 'speedomatic/src/unfix' {
  declare module.exports: any;
}

declare module 'speedomatic/src/unfork' {
  declare module.exports: any;
}

declare module 'speedomatic/src/unroll-array' {
  declare module.exports: any;
}

declare module 'speedomatic/src/wrap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'speedomatic/exports.js' {
  declare module.exports: $Exports<'speedomatic/exports'>;
}
declare module 'speedomatic/src/abi-decode-bytes.js' {
  declare module.exports: $Exports<'speedomatic/src/abi-decode-bytes'>;
}
declare module 'speedomatic/src/abi-decode-data.js' {
  declare module.exports: $Exports<'speedomatic/src/abi-decode-data'>;
}
declare module 'speedomatic/src/abi-decode-rpc-response.js' {
  declare module.exports: $Exports<'speedomatic/src/abi-decode-rpc-response'>;
}
declare module 'speedomatic/src/abi-decode-short-string-as-int256.js' {
  declare module.exports: $Exports<'speedomatic/src/abi-decode-short-string-as-int256'>;
}
declare module 'speedomatic/src/abi-encode-bytes.js' {
  declare module.exports: $Exports<'speedomatic/src/abi-encode-bytes'>;
}
declare module 'speedomatic/src/abi-encode-data.js' {
  declare module.exports: $Exports<'speedomatic/src/abi-encode-data'>;
}
declare module 'speedomatic/src/abi-encode-int256.js' {
  declare module.exports: $Exports<'speedomatic/src/abi-encode-int256'>;
}
declare module 'speedomatic/src/abi-encode-short-string-as-int256.js' {
  declare module.exports: $Exports<'speedomatic/src/abi-encode-short-string-as-int256'>;
}
declare module 'speedomatic/src/abi-encode-transaction-payload.js' {
  declare module.exports: $Exports<'speedomatic/src/abi-encode-transaction-payload'>;
}
declare module 'speedomatic/src/bignum.js' {
  declare module.exports: $Exports<'speedomatic/src/bignum'>;
}
declare module 'speedomatic/src/byte-array-to-hex-string.js' {
  declare module.exports: $Exports<'speedomatic/src/byte-array-to-hex-string'>;
}
declare module 'speedomatic/src/byte-array-to-utf8-string.js' {
  declare module.exports: $Exports<'speedomatic/src/byte-array-to-utf8-string'>;
}
declare module 'speedomatic/src/chunk.js' {
  declare module.exports: $Exports<'speedomatic/src/chunk'>;
}
declare module 'speedomatic/src/constants.js' {
  declare module.exports: $Exports<'speedomatic/src/constants'>;
}
declare module 'speedomatic/src/encode-number-as-base10-string.js' {
  declare module.exports: $Exports<'speedomatic/src/encode-number-as-base10-string'>;
}
declare module 'speedomatic/src/encode-number-as-js-number.js' {
  declare module.exports: $Exports<'speedomatic/src/encode-number-as-js-number'>;
}
declare module 'speedomatic/src/fix.js' {
  declare module.exports: $Exports<'speedomatic/src/fix'>;
}
declare module 'speedomatic/src/format-abi-raw-decoded-data-array.js' {
  declare module.exports: $Exports<'speedomatic/src/format-abi-raw-decoded-data-array'>;
}
declare module 'speedomatic/src/format-abi-raw-decoded-data.js' {
  declare module.exports: $Exports<'speedomatic/src/format-abi-raw-decoded-data'>;
}
declare module 'speedomatic/src/format-ethereum-address.js' {
  declare module.exports: $Exports<'speedomatic/src/format-ethereum-address'>;
}
declare module 'speedomatic/src/format-int256.js' {
  declare module.exports: $Exports<'speedomatic/src/format-int256'>;
}
declare module 'speedomatic/src/hex.js' {
  declare module.exports: $Exports<'speedomatic/src/hex'>;
}
declare module 'speedomatic/src/index.js' {
  declare module.exports: $Exports<'speedomatic/src/index'>;
}
declare module 'speedomatic/src/is-hex.js' {
  declare module.exports: $Exports<'speedomatic/src/is-hex'>;
}
declare module 'speedomatic/src/pad-left.js' {
  declare module.exports: $Exports<'speedomatic/src/pad-left'>;
}
declare module 'speedomatic/src/pad-right.js' {
  declare module.exports: $Exports<'speedomatic/src/pad-right'>;
}
declare module 'speedomatic/src/prefix-hex.js' {
  declare module.exports: $Exports<'speedomatic/src/prefix-hex'>;
}
declare module 'speedomatic/src/remove-trailing-zeros.js' {
  declare module.exports: $Exports<'speedomatic/src/remove-trailing-zeros'>;
}
declare module 'speedomatic/src/serialize.js' {
  declare module.exports: $Exports<'speedomatic/src/serialize'>;
}
declare module 'speedomatic/src/strip-0x-prefix.js' {
  declare module.exports: $Exports<'speedomatic/src/strip-0x-prefix'>;
}
declare module 'speedomatic/src/unfix-signed.js' {
  declare module.exports: $Exports<'speedomatic/src/unfix-signed'>;
}
declare module 'speedomatic/src/unfix.js' {
  declare module.exports: $Exports<'speedomatic/src/unfix'>;
}
declare module 'speedomatic/src/unfork.js' {
  declare module.exports: $Exports<'speedomatic/src/unfork'>;
}
declare module 'speedomatic/src/unroll-array.js' {
  declare module.exports: $Exports<'speedomatic/src/unroll-array'>;
}
declare module 'speedomatic/src/wrap.js' {
  declare module.exports: $Exports<'speedomatic/src/wrap'>;
}
